-- CYP-220 Phase 6 S5 — AgentEventStore (agent_events) PG schema. The per-agent stream-json transcript,
-- already MASKED (Gate #3), NON-SECRET. APPEND-ONLY. seq is a DB-generated identity → gapless, monotonic,
-- NEVER reused even after retention deletes (a MAX(seq)+1 counter would reuse once the top agent is trimmed).
CREATE TABLE IF NOT EXISTS agent_events (
    seq        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id   TEXT   NOT NULL,
    project_id TEXT   NOT NULL,
    ts         BIGINT NOT NULL,
    event_json TEXT   NOT NULL
);

-- The replay/backfill path is WHERE agent_id=? AND seq>? ORDER BY seq — index-served by (agent_id, seq).
CREATE INDEX IF NOT EXISTS idx_agentevents_agent_seq ON agent_events (agent_id, seq);
CREATE INDEX IF NOT EXISTS idx_agentevents_project ON agent_events (project_id);
