// CYP-843 — the zod-gen nullable-ENUM fix, proven behaviorally on the generated schema. json-schema-to-zod's enum
// branch dropped the null branch of a `type:[<enum>,"null"]` field, so a contract-conformant explicit `null` (kotlinx
// accepts it) was wrongly rejected — and under CYP-834 that would FALSE-TERMINAL-skew a valid frame (meta.kind:null).
// The fix rewrites a nullable enum to `z.union([z.enum([...]), z.null()])` so null validates, WITHOUT loosening the
// closed value set. These teeth ride the generated CommWsServerEventSchema (regenerated by zod:gen at build).
import { describe, it, expect } from 'vitest'
import { CommWsServerEventSchema } from '../types/generated/contractSchemas'

const msg = (meta: unknown) => ({
  type: 'message',
  delivered: { message: { id: 'm', channelId: 'c', from: 'a', body: 'hi', ts: 1, meta } },
})

describe('CYP-843 — nullable enum accepts explicit null (kotlinx-parity, no false-skew) yet still rejects out-of-set', () => {
  it('★ meta.kind: null → VALID (the fix — a nullable enum must accept explicit null; before, it false-skewed)', () => {
    // MUT: revert the codegen (drop fixNullableEnums → z.enum([...]).optional()) + regenerate → kind:null fails; reds.
    expect(CommWsServerEventSchema.safeParse(msg({ kind: null })).success).toBe(true)
  })

  it('★ meta.kind: "TASK" → VALID (a known enum value still passes)', () => {
    expect(CommWsServerEventSchema.safeParse(msg({ kind: 'TASK' })).success).toBe(true)
  })

  it('★ meta.kind ABSENT → VALID (optional)', () => {
    expect(CommWsServerEventSchema.safeParse(msg({})).success).toBe(true)
  })

  it('★ meta.kind: "BOGUS" → INVALID (nullability did NOT widen the closed enum — an unknown value is still a skew)', () => {
    expect(CommWsServerEventSchema.safeParse(msg({ kind: 'BOGUS' })).success).toBe(false)
  })

  it('★ meta.inReplyTo: null → VALID (plain nullable string was already correct — regression guard for the general rule)', () => {
    expect(CommWsServerEventSchema.safeParse(msg({ inReplyTo: null })).success).toBe(true)
  })
})
