// CYP-423 (Maritime token layer) — the SINGLE source of the maritime M3 palette for web-ts, ported 1:1 from the
// Compose scheme `app/shared/.../ui/MaritimeTheme.kt` (UIUX-ratified tokens; MaritimeLight = CYP-268, MaritimeDark
// = CYP-304 night). 24 roles per scheme. Kept as .mjs (with a .d.mts) so BOTH the CSS generator (Node) and the TS
// app + guard test read the exact same values — no drift, and the a11y contrast guard measures what ships.
// "Port tokens, not optics": these are the wire values; do not re-eyeball them.
export const MARITIME_TOKENS = {
  light: {
    primary: '#0A5AA0',
    onPrimary: '#FFFFFF',
    primaryContainer: '#BEE0FA',
    onPrimaryContainer: '#04263F',
    secondary: '#0F5B88',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#C4E2F5',
    onSecondaryContainer: '#06283D',
    tertiary: '#0B7E9C',
    onTertiary: '#FFFFFF',
    tertiaryContainer: '#B7E7F2',
    onTertiaryContainer: '#022E3B',
    error: '#B3261E',
    onError: '#FFFFFF',
    errorContainer: '#F9DEDC',
    onErrorContainer: '#410E0B',
    background: '#FFFFFF',
    onBackground: '#0C2635',
    surface: '#FFFFFF',
    onSurface: '#0C2635',
    surfaceVariant: '#E4EFF8',
    onSurfaceVariant: '#3A4E5A',
    outline: '#6E8C9E',
    outlineVariant: '#CBDCE7',
  },
  dark: {
    primary: '#6FBEEA',
    onPrimary: '#02324E',
    primaryContainer: '#0A4E7C',
    onPrimaryContainer: '#C7E6FB',
    secondary: '#93CCEA',
    onSecondary: '#052A3F',
    secondaryContainer: '#154F70',
    onSecondaryContainer: '#C7E6FB',
    tertiary: '#40D6A0',
    onTertiary: '#04322A',
    tertiaryContainer: '#0C3D30',
    onTertiaryContainer: '#9EEAD0',
    error: '#F2B8B5',
    onError: '#601410',
    errorContainer: '#8C1D18',
    onErrorContainer: '#F9DEDC',
    background: '#06121A',
    onBackground: '#DCE7ED',
    surface: '#06121A',
    onSurface: '#DCE7ED',
    surfaceVariant: '#12242F',
    onSurfaceVariant: '#A6BECD',
    outline: '#57707F',
    outlineVariant: '#243642',
  },
}
