package com.tneff.cyppieagents.agentevents

import com.tneff.cyppieagents.CommJson
import com.tneff.cyppieagents.db.FlywayMigrator
import com.tneff.cyppieagents.db.MigrationRowCodec
import com.tneff.cyppieagents.db.MigrationTarget
import com.tneff.cyppieagents.model.StoredAgentEvent
import com.tneff.cyppieagents.model.StreamJsonEvent
import java.sql.Connection
import javax.sql.DataSource
import kotlinx.coroutines.CoroutineDispatcher
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.channels.BufferOverflow
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableSharedFlow
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.withContext
import org.slf4j.LoggerFactory

/**
 * CYP-220 Phase 6 S5 — the **Postgres** [AgentEventStore]. Behaviour-identical to
 * [SqliteAgentEventStore]: `seq` is a **DB-generated identity** (`GENERATED BY DEFAULT AS IDENTITY`) →
 * gapless, monotonic, **never reused even after retention deletes** (a `MAX(seq)+1` counter would reuse a seq
 * once the top agent's rows are trimmed — the identity never does); one live [MutableSharedFlow] fan-out; the
 * SAME replay-then-live [subscribe] with the `seq > cursor` dedup guard (CYP-198 race fix); LOSSLESS within
 * [retainPerAgent]. **Append-only ⇒ RMW-immune** (no `FOR UPDATE`). High-volume, so the `(agent_id, seq)`
 * index carries the replay/backfill path.
 *
 * The [mutex] serialises append (the RETURNING-seq insert + the retention delete + the emit) so a subscriber's
 * cursor never sees a gap; JDBC on [io]; reads are lock-free (Postgres MVCC).
 */
class PgAgentEventStore(
    private val dataSource: DataSource,
    private val retainPerAgent: Int = InMemoryAgentEventStore.DEFAULT_RETAIN_PER_AGENT,
    private val io: CoroutineDispatcher = Dispatchers.IO,
    migrate: Boolean = true,
) : AgentEventStore, MigrationTarget, AutoCloseable {
    private val log = LoggerFactory.getLogger("agentevents.pg")
    private val mutex = Mutex()
    private val live = MutableSharedFlow<StoredAgentEvent>(extraBufferCapacity = 256, onBufferOverflow = BufferOverflow.DROP_OLDEST)

    init { if (migrate) FlywayMigrator.migrate(dataSource, "classpath:db/migration/agentevents") }

    override suspend fun append(agentId: String, projectId: String, tsMs: Long, event: StreamJsonEvent): StoredAgentEvent {
        val json = CommJson.encodeToString(StreamJsonEvent.serializer(), event)
        val stored = withContext(io) {
            mutex.withLock {
                tx { c ->
                    val seq = c.prepareStatement(
                        "INSERT INTO agent_events(agent_id, project_id, ts, event_json) VALUES (?,?,?,?) RETURNING seq",
                    ).use { ps ->
                        ps.setString(1, agentId); ps.setString(2, projectId); ps.setLong(3, tsMs); ps.setString(4, json)
                        ps.executeQuery().use { rs -> rs.next(); rs.getLong(1) }
                    }
                    // Retention: keep the last [retainPerAgent] rows for this agent (lossless within the window).
                    if (retainPerAgent > 0) {
                        c.prepareStatement(
                            "DELETE FROM agent_events WHERE agent_id=? AND seq NOT IN " +
                                "(SELECT seq FROM agent_events WHERE agent_id=? ORDER BY seq DESC LIMIT ?)",
                        ).use { ps -> ps.setString(1, agentId); ps.setString(2, agentId); ps.setInt(3, retainPerAgent); ps.executeUpdate() }
                    }
                    StoredAgentEvent(seq, agentId, projectId, tsMs, event)
                }
            }
        }
        live.tryEmit(stored)
        return stored
    }

    // CYP-198 race fix + CYP-588 GAP-DETECT (DROP_OLDEST live drop under a slow consumer → re-query + backfill),
    // single-sourced in [agentEventReplayThenLive] (identical to Sqlite — the drift the shared body prevents).
    override fun subscribe(agentId: String, sinceSeq: Long?): Flow<StoredAgentEvent> =
        agentEventReplayThenLive(agentId, sinceSeq, live, ::query) { from, to ->
            log.warn("CYP-588: live-buffer gap seq {}..{} (slow consumer + DROP_OLDEST) — backfilled from the durable store: agent={}", from, to, agentId)
        }

    override suspend fun query(agentId: String, sinceSeq: Long?, limit: Int): List<StoredAgentEvent> = withContext(io) {
        dataSource.connection.use { c ->
            c.prepareStatement(
                "SELECT seq, agent_id, project_id, ts, event_json FROM agent_events WHERE agent_id=? AND seq>? ORDER BY seq ASC LIMIT ?",
            ).use { ps ->
                ps.setString(1, agentId); ps.setLong(2, sinceSeq ?: 0L); ps.setInt(3, limit.coerceIn(0, Int.MAX_VALUE))
                ps.executeQuery().use { rs ->
                    buildList {
                        while (rs.next()) {
                            val seq = rs.getLong(1)
                            // CYP-579: an undecodable row (schema-drift / corrupt) was silently skipped → a `/ws/agent`
                            // replay gap with no signal (CYP-575 class). Now: WARN + emit an "unrenderable" placeholder at
                            // the SAME seq so the gap is visible (cursor/dedup intact). Identical to the Sqlite path.
                            val ev = runCatching { CommJson.decodeFromString(StreamJsonEvent.serializer(), rs.getString(5)) }
                                .onFailure { log.warn("CYP-579: undecodable agent_event seq={} agent={} — emitting unrenderable placeholder", seq, agentId, it) }
                                .getOrElse { unrenderableEventPlaceholder(seq) }
                            add(StoredAgentEvent(seq, rs.getString(2), rs.getString(3), rs.getLong(4), ev))
                        }
                    }
                }
            }
        }
    }

    override suspend fun deleteByProject(projectId: String): Int = withContext(io) {
        tx { c ->
            c.prepareStatement("DELETE FROM agent_events WHERE project_id=?").use { ps -> ps.setString(1, projectId); ps.executeUpdate() }
        }
    }

    // ---- MigrationTarget (canonical rows: [seq, agent_id, project_id, ts, event_json]) ----

    override fun exportRows(): List<ByteArray> = dataSource.connection.use { c ->
        c.prepareStatement("SELECT seq, agent_id, project_id, ts, event_json FROM agent_events ORDER BY seq ASC").use { st ->
            st.executeQuery().use { rs ->
                buildList {
                    while (rs.next()) add(MigrationRowCodec.encode(listOf(rs.getLong(1).toString(), rs.getString(2), rs.getString(3), rs.getLong(4).toString(), rs.getString(5))))
                }
            }
        }
    }

    override fun importRows(rows: List<ByteArray>) {
        tx { c ->
            c.prepareStatement("DELETE FROM agent_events").use { it.executeUpdate() }
            // preserve the source seq exactly (identity accepts an explicit value with GENERATED BY DEFAULT).
            c.prepareStatement("INSERT INTO agent_events(seq, agent_id, project_id, ts, event_json) VALUES (?,?,?,?,?)").use { ps ->
                for (row in rows) {
                    val f = MigrationRowCodec.decode(row) // [seq, agentId, projectId, ts, eventJson]
                    ps.setLong(1, f[0].toLong()); ps.setString(2, f[1]); ps.setString(3, f[2]); ps.setLong(4, f[3].toLong()); ps.setString(5, f[4])
                    ps.addBatch()
                }
                ps.executeBatch()
            }
            // realign the identity so future appends don't collide with imported seqs.
            c.prepareStatement("SELECT setval(pg_get_serial_sequence('agent_events','seq'), COALESCE((SELECT MAX(seq) FROM agent_events), 1))").use { it.executeQuery().use { rs -> rs.next() } }
        }
    }

    override fun close() {}

    private fun <T> tx(block: (Connection) -> T): T = dataSource.connection.use { c ->
        val prev = c.autoCommit
        c.autoCommit = false
        try {
            val r = block(c); c.commit(); r
        } catch (e: Throwable) {
            runCatching { c.rollback() }; throw e
        } finally {
            runCatching { c.autoCommit = prev }
        }
    }
}
