#!/usr/bin/env bash
# CyppieAgents — local-dev bootstrap (CYP-46)
#
# Generates a local `.env` with random dev tokens and a local `platform.config.json`,
# so a fresh clone can boot the server without hand-editing secrets.
#
#   ./scripts/dev-setup.sh
#
# Safe by default: never overwrites an existing `.env` or `platform.config.json`
# (pass --force to regenerate). Token VALUES are never printed.
set -euo pipefail

# Resolve repo root (this script lives in <root>/scripts).
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

FORCE=0
[ "${1:-}" = "--force" ] && FORCE=1

# --- preconditions ----------------------------------------------------------
command -v openssl >/dev/null 2>&1 || {
  echo "ERROR: openssl not found — needed to generate tokens. Install it and retry." >&2
  exit 1
}

gen() { openssl rand -hex 32; }

# --- .env -------------------------------------------------------------------
if [ -f .env ] && [ "$FORCE" -ne 1 ]; then
  echo "• .env already exists — leaving it untouched (use --force to regenerate)."
else
  umask 077  # the .env must not be world-readable
  cat > .env <<EOF
# Local dev env generated by scripts/dev-setup.sh — DO NOT COMMIT.
# Regenerate any time with:  ./scripts/dev-setup.sh --force
# Token values are random per-machine. See .env.example for the documented reference.

# Server (required, fail-closed) — one bearer per agent + the operator token.
HUB_TOKEN_PO=$(gen)
HUB_TOKEN_FRONTEND=$(gen)
HUB_TOKEN_BACKEND=$(gen)
OPERATOR_TOKEN=$(gen)

# Server (optional) — defaults shown; uncomment to override.
# PLATFORM_CONFIG=platform.config.json
PLATFORM_GIT_ROOT=.cyppie

# Real agent run only (optional): defaults to OAuth subscription creds (~/.claude).
# ANTHROPIC_API_KEY=

# Desktop/JVM client (optional) — defaults localhost:8787.
# HUB_HOST=localhost
# HUB_PORT=8787
EOF
  echo "• wrote .env with fresh random dev tokens (chmod 600, values not printed)."
fi

# --- platform.config.json ---------------------------------------------------
if [ -f platform.config.json ] && [ "$FORCE" -ne 1 ]; then
  echo "• platform.config.json already exists — leaving it untouched."
elif [ -f platform.config.example.json ]; then
  cp platform.config.example.json platform.config.json
  echo "• copied platform.config.example.json → platform.config.json."
  echo "  ⚠ Edit \"repo.url\": the boot CLONES it as a hard prerequisite. The example"
  echo "    placeholder will abort the boot. For a credential-free local boot, point it at"
  echo "    a local repo, e.g.  \"url\": \"file://$ROOT\"  with an existing \"branch\"."
else
  echo "• platform.config.example.json not found — skipping config copy." >&2
fi

cat <<'EOF'

Next:
  1) Review platform.config.json (especially repo.url + branch).
  2) Load the env into your shell:   set -a; . ./.env; set +a
  3) Start the server:               ./gradlew :server:run
  4) Start the desktop UI:           ./gradlew :app:desktopApp:run
See docs/SETUP.md for the full walkthrough (incl. the zero-setup web UI preview).
EOF
